FROM ubuntu:20.04
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get install -y \
    fortune cowsay \
    && apt-get clean
    WORKDIR /app
    COPY . .
    RUN chmod +x wisecow.sh
    EXPOSE 4499
    CMD ["./wisecow.sh"]